name: Check Links

on:
  push:
  schedule: 
    - cron: "0 0 1 */2 *"

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - name: Setup repo
              uses: actions/checkout@v2

            - name: Check Links
              uses: peter-evans/link-checker@v1.2.2
              with:
                args: -r *

            - name: Update gist
              uses: popsiclestick/gist-sync-action@v1.0.0
              with:
                  auth: ${{ secrets.GH_TOKEN }}
                  gist_url: https://gist.github.com/maximousblk/4d3af38b6491002d93fab464ad6a9e00
                  gist_title: link-checker.log.md
                  gist_description: Piracy list Link Checker Report
                  github_file: ./link-checker/out.md