name: Check Links

on:
  push:
  schedule: 
    - cron: "0 0 1 */2 *"

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - name: Setup repo
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                node-version: '12'

            - name: Install link checker
              run: npm i -g markdown-link-check

            # - name: Check Links
            #   uses: peter-evans/link-checker@v1.2.2
            #   with:
            #     args: -r * -c 64

            - name: Check links
              run: find . -name \*.md -exec markdown-link-check -q {} \; | tee issue.md

            - name: Close Old Issue
              uses: bdougie/close-issues-based-on-label@master
              env:
                LABEL: bad links
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Create New Issue
              uses: peter-evans/create-issue-from-file@v2
              with:
                title: bad Links
                content-filepath: ./issue.md
                labels: bad links
