name: Archive website

on:
  push:
    branches: [ master ]

jobs:
  archive:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install archivenow
    - name: Archive pages
      run: |
        archivenow --ia https://piracy.now.sh/
        archivenow --ia https://piracy.now.sh/about/
        archivenow --ia https://piracy.now.sh/security/
        archivenow --ia https://piracy.now.sh/laws/
        archivenow --ia https://piracy.now.sh/dead/
        archivenow --ia https://maximousblk.github.io/piracy/
